# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QTabWidget,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(481, 336)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush1)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush1)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush1)
        brush2 = QBrush(QColor(255, 255, 220, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush2)
        brush3 = QBrush(QColor(255, 255, 255, 127))
        brush3.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush2)
        brush4 = QBrush(QColor(0, 0, 0, 127))
        brush4.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush4)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.Accent, brush1)
        MainWindow.setPalette(palette)
        self.menu_new = QAction(MainWindow)
        self.menu_new.setObjectName(u"menu_new")
        self.menu_open = QAction(MainWindow)
        self.menu_open.setObjectName(u"menu_open")
        self.menu_about = QAction(MainWindow)
        self.menu_about.setObjectName(u"menu_about")
        self.menu_exit = QAction(MainWindow)
        self.menu_exit.setObjectName(u"menu_exit")
        self.menu_solve = QAction(MainWindow)
        self.menu_solve.setObjectName(u"menu_solve")
        self.menu_help = QAction(MainWindow)
        self.menu_help.setObjectName(u"menu_help")
        self.menu_theme = QAction(MainWindow)
        self.menu_theme.setObjectName(u"menu_theme")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 481, 351))
        self.tabWidget.setBaseSize(QSize(0, 0))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        brush5 = QBrush(QColor(15, 16, 17, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush5)
        brush6 = QBrush(QColor(20, 21, 23, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush6)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush2)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette1.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush7 = QBrush(QColor(15, 16, 17, 127))
        brush7.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush7)
#endif
        brush8 = QBrush(QColor(21, 22, 24, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.Accent, brush8)
        self.tabWidget.setPalette(palette1)
        font = QFont()
        font.setFamilies([u"Terminal"])
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setToolTipDuration(3)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.tab_1.setPalette(palette2)
        self.tab_1.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.lbl_clock_iran = QLabel(self.tab_1)
        self.lbl_clock_iran.setObjectName(u"lbl_clock_iran")
        self.lbl_clock_iran.setGeometry(QRect(220, 12, 261, 91))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush9 = QBrush(QColor(37, 63, 75, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush9)
        brush10 = QBrush(QColor(31, 52, 62, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        brush11 = QBrush(QColor(12, 21, 25, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush11)
        brush12 = QBrush(QColor(17, 28, 33, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette3.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush2)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette3.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette3.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        brush13 = QBrush(QColor(25, 42, 50, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush2)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush14 = QBrush(QColor(12, 21, 25, 127))
        brush14.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush14)
#endif
        brush15 = QBrush(QColor(18, 30, 35, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Disabled, QPalette.Accent, brush15)
        self.lbl_clock_iran.setPalette(palette3)
        font1 = QFont()
        font1.setFamilies([u"FS Sevegment"])
        font1.setPointSize(42)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setUnderline(False)
        font1.setStrikeOut(False)
        self.lbl_clock_iran.setFont(font1)
        self.lbl_clock_iran.setStyleSheet(u"color: rgb(255, 170, 0);")
        self.lbl_clock_iran.setAlignment(Qt.AlignCenter)
        self.lbl_clock_germany = QLabel(self.tab_1)
        self.lbl_clock_germany.setObjectName(u"lbl_clock_germany")
        self.lbl_clock_germany.setGeometry(QRect(220, 110, 261, 90))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette4.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette4.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette4.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette4.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipBase, brush2)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette4.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette4.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette4.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette4.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette4.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        palette4.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette4.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette4.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette4.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette4.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush14)
#endif
        palette4.setBrush(QPalette.Disabled, QPalette.Accent, brush15)
        self.lbl_clock_germany.setPalette(palette4)
        self.lbl_clock_germany.setFont(font1)
        self.lbl_clock_germany.setStyleSheet(u"color: rgb(255, 170, 0);")
        self.lbl_clock_germany.setAlignment(Qt.AlignCenter)
        self.lbl_clock_usa = QLabel(self.tab_1)
        self.lbl_clock_usa.setObjectName(u"lbl_clock_usa")
        self.lbl_clock_usa.setGeometry(QRect(220, 200, 261, 111))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette5.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette5.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette5.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush)
        palette5.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette5.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipBase, brush2)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette5.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette5.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette5.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette5.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette5.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette5.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette5.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette5.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette5.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush14)
#endif
        palette5.setBrush(QPalette.Disabled, QPalette.Accent, brush15)
        self.lbl_clock_usa.setPalette(palette5)
        self.lbl_clock_usa.setFont(font1)
        self.lbl_clock_usa.setStyleSheet(u"color: rgb(255, 170, 0);")
        self.lbl_clock_usa.setAlignment(Qt.AlignCenter)
        self.lbl_iran = QLabel(self.tab_1)
        self.lbl_iran.setObjectName(u"lbl_iran")
        self.lbl_iran.setGeometry(QRect(10, 12, 211, 81))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette6.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette6.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette6.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush)
        palette6.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette6.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette6.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipBase, brush2)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette6.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette6.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette6.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette6.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette6.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette6.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette6.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette6.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette6.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette6.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush2)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush14)
#endif
        palette6.setBrush(QPalette.Disabled, QPalette.Accent, brush15)
        self.lbl_iran.setPalette(palette6)
        font2 = QFont()
        font2.setFamilies([u"Comic Sans MS"])
        font2.setPointSize(36)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setUnderline(False)
        font2.setStrikeOut(False)
        self.lbl_iran.setFont(font2)
        self.lbl_iran.setStyleSheet(u"")
        self.lbl_iran.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lbl_germany = QLabel(self.tab_1)
        self.lbl_germany.setObjectName(u"lbl_germany")
        self.lbl_germany.setGeometry(QRect(10, 110, 211, 81))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette7.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette7.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette7.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush)
        palette7.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette7.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipBase, brush2)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette7.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette7.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette7.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette7.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        palette7.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette7.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette7.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette7.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette7.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette7.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush14)
#endif
        palette7.setBrush(QPalette.Disabled, QPalette.Accent, brush15)
        self.lbl_germany.setPalette(palette7)
        self.lbl_germany.setFont(font2)
        self.lbl_germany.setStyleSheet(u"")
        self.lbl_germany.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lbl_usa = QLabel(self.tab_1)
        self.lbl_usa.setObjectName(u"lbl_usa")
        self.lbl_usa.setGeometry(QRect(10, 210, 211, 81))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette8.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette8.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette8.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush)
        palette8.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette8.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette8.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipBase, brush2)
        palette8.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette8.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette8.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette8.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette8.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette8.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        palette8.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette8.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette8.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette8.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette8.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette8.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette8.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush14)
#endif
        palette8.setBrush(QPalette.Disabled, QPalette.Accent, brush15)
        self.lbl_usa.setPalette(palette8)
        font3 = QFont()
        font3.setFamilies([u"Comic Sans MS"])
        font3.setPointSize(33)
        font3.setBold(True)
        font3.setItalic(False)
        font3.setUnderline(False)
        font3.setStrikeOut(False)
        self.lbl_usa.setFont(font3)
        self.lbl_usa.setStyleSheet(u"")
        self.lbl_usa.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tab_2.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.gridLayoutWidget = QWidget(self.tab_2)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(9, 9, 441, 281))
        self.gl_alarms = QGridLayout(self.gridLayoutWidget)
        self.gl_alarms.setObjectName(u"gl_alarms")
        self.gl_alarms.setContentsMargins(0, 0, 0, 0)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.tab_3.setPalette(palette9)
        self.tab_3.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.btn_reset_timer = QPushButton(self.tab_3)
        self.btn_reset_timer.setObjectName(u"btn_reset_timer")
        self.btn_reset_timer.setGeometry(QRect(310, 180, 131, 51))
        font4 = QFont()
        font4.setFamilies([u"Digital-7"])
        font4.setPointSize(22)
        font4.setBold(False)
        font4.setItalic(False)
        font4.setUnderline(False)
        font4.setStrikeOut(False)
        self.btn_reset_timer.setFont(font4)
        self.btn_reset_timer.setStyleSheet(u"background-color: rgb(255, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.btn_start_timer = QPushButton(self.tab_3)
        self.btn_start_timer.setObjectName(u"btn_start_timer")
        self.btn_start_timer.setGeometry(QRect(30, 180, 131, 51))
        self.btn_start_timer.setFont(font4)
        self.btn_start_timer.setStyleSheet(u"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.btn_stop_timer = QPushButton(self.tab_3)
        self.btn_stop_timer.setObjectName(u"btn_stop_timer")
        self.btn_stop_timer.setGeometry(QRect(170, 180, 131, 51))
        self.btn_stop_timer.setFont(font4)
        self.btn_stop_timer.setStyleSheet(u"background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.tb_hour_timer = QLineEdit(self.tab_3)
        self.tb_hour_timer.setObjectName(u"tb_hour_timer")
        self.tb_hour_timer.setGeometry(QRect(87, 31, 101, 91))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush16 = QBrush(QColor(255, 0, 127, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush16)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush16)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.tb_hour_timer.setPalette(palette10)
        font5 = QFont()
        font5.setFamilies([u"FS Sevegment"])
        font5.setPointSize(50)
        font5.setBold(False)
        font5.setItalic(False)
        font5.setUnderline(False)
        font5.setStrikeOut(False)
        self.tb_hour_timer.setFont(font5)
        self.tb_hour_timer.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.tb_hour_timer.setAlignment(Qt.AlignCenter)
        self.tb_minute_timer = QLineEdit(self.tab_3)
        self.tb_minute_timer.setObjectName(u"tb_minute_timer")
        self.tb_minute_timer.setGeometry(QRect(188, 31, 101, 91))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Active, QPalette.Text, brush16)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.Text, brush16)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.tb_minute_timer.setPalette(palette11)
        self.tb_minute_timer.setFont(font5)
        self.tb_minute_timer.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.tb_minute_timer.setAlignment(Qt.AlignCenter)
        self.tb_second_timer = QLineEdit(self.tab_3)
        self.tb_second_timer.setObjectName(u"tb_second_timer")
        self.tb_second_timer.setGeometry(QRect(289, 31, 101, 91))
        palette12 = QPalette()
        palette12.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Active, QPalette.Text, brush16)
        palette12.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette12.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Text, brush16)
        palette12.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette12.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette12.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        self.tb_second_timer.setPalette(palette12)
        self.tb_second_timer.setFont(font5)
        self.tb_second_timer.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.tb_second_timer.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_3, "")
        self.btn_reset_timer.raise_()
        self.btn_start_timer.raise_()
        self.btn_stop_timer.raise_()
        self.tb_second_timer.raise_()
        self.tb_minute_timer.raise_()
        self.tb_hour_timer.raise_()
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        palette13 = QPalette()
        brush17 = QBrush(QColor(36, 36, 35, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush17)
        palette13.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush18 = QBrush(QColor(70, 70, 69, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette13.setBrush(QPalette.Active, QPalette.Light, brush18)
        brush19 = QBrush(QColor(58, 58, 57, 255))
        brush19.setStyle(Qt.SolidPattern)
        palette13.setBrush(QPalette.Active, QPalette.Midlight, brush19)
        brush20 = QBrush(QColor(23, 23, 23, 255))
        brush20.setStyle(Qt.SolidPattern)
        palette13.setBrush(QPalette.Active, QPalette.Dark, brush20)
        brush21 = QBrush(QColor(31, 31, 31, 255))
        brush21.setStyle(Qt.SolidPattern)
        palette13.setBrush(QPalette.Active, QPalette.Mid, brush21)
        palette13.setBrush(QPalette.Active, QPalette.Text, brush)
        palette13.setBrush(QPalette.Active, QPalette.BrightText, brush)
        brush22 = QBrush(QColor(51, 51, 50, 255))
        brush22.setStyle(Qt.SolidPattern)
        palette13.setBrush(QPalette.Active, QPalette.ButtonText, brush22)
        palette13.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette13.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette13.setBrush(QPalette.Active, QPalette.AlternateBase, brush20)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipBase, brush2)
        palette13.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette13.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush17)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Light, brush18)
        palette13.setBrush(QPalette.Inactive, QPalette.Midlight, brush19)
        palette13.setBrush(QPalette.Inactive, QPalette.Dark, brush20)
        palette13.setBrush(QPalette.Inactive, QPalette.Mid, brush21)
        palette13.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette13.setBrush(QPalette.Inactive, QPalette.ButtonText, brush22)
        palette13.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette13.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush20)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush2)
        palette13.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        palette13.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush20)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Light, brush18)
        palette13.setBrush(QPalette.Disabled, QPalette.Midlight, brush19)
        palette13.setBrush(QPalette.Disabled, QPalette.Dark, brush20)
        palette13.setBrush(QPalette.Disabled, QPalette.Mid, brush21)
        palette13.setBrush(QPalette.Disabled, QPalette.Text, brush20)
        palette13.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette13.setBrush(QPalette.Disabled, QPalette.ButtonText, brush20)
        palette13.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette13.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        brush23 = QBrush(QColor(47, 47, 46, 255))
        brush23.setStyle(Qt.SolidPattern)
        palette13.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush23)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush2)
        palette13.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
        brush24 = QBrush(QColor(23, 23, 23, 127))
        brush24.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette13.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush24)
#endif
        brush25 = QBrush(QColor(33, 33, 32, 255))
        brush25.setStyle(Qt.SolidPattern)
        palette13.setBrush(QPalette.Disabled, QPalette.Accent, brush25)
        self.tab_4.setPalette(palette13)
        self.tab_4.setAutoFillBackground(False)
        self.tab_4.setStyleSheet(u"background-color:rgba(0, 0, 0, 255)")
        self.lbl_stopwatch = QLabel(self.tab_4)
        self.lbl_stopwatch.setObjectName(u"lbl_stopwatch")
        self.lbl_stopwatch.setGeometry(QRect(48, 36, 381, 81))
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Active, QPalette.Light, brush9)
        palette14.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette14.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette14.setBrush(QPalette.Active, QPalette.Mid, brush12)
        palette14.setBrush(QPalette.Active, QPalette.Text, brush)
        palette14.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette14.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette14.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette14.setBrush(QPalette.Active, QPalette.Shadow, brush1)
        palette14.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        palette14.setBrush(QPalette.Active, QPalette.ToolTipBase, brush2)
        palette14.setBrush(QPalette.Active, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Active, QPalette.PlaceholderText, brush3)
#endif
        palette14.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Light, brush9)
        palette14.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette14.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette14.setBrush(QPalette.Inactive, QPalette.Mid, brush12)
        palette14.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.BrightText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.Shadow, brush1)
        palette14.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette14.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush2)
        palette14.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush3)
#endif
        palette14.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush11)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.Light, brush9)
        palette14.setBrush(QPalette.Disabled, QPalette.Midlight, brush10)
        palette14.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette14.setBrush(QPalette.Disabled, QPalette.Mid, brush12)
        palette14.setBrush(QPalette.Disabled, QPalette.Text, brush11)
        palette14.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.ButtonText, brush11)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.Shadow, brush1)
        palette14.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette14.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush2)
        palette14.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette14.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush14)
#endif
        palette14.setBrush(QPalette.Disabled, QPalette.Accent, brush15)
        self.lbl_stopwatch.setPalette(palette14)
        self.lbl_stopwatch.setFont(font5)
        self.lbl_stopwatch.setStyleSheet(u"color: rgb(255, 0, 127);")
        self.lbl_stopwatch.setAlignment(Qt.AlignCenter)
        self.btn_start_stopwatch = QPushButton(self.tab_4)
        self.btn_start_stopwatch.setObjectName(u"btn_start_stopwatch")
        self.btn_start_stopwatch.setGeometry(QRect(30, 180, 131, 51))
        self.btn_start_stopwatch.setFont(font4)
        self.btn_start_stopwatch.setStyleSheet(u"background-color: rgb(255, 170, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.btn_stop_stopwatch = QPushButton(self.tab_4)
        self.btn_stop_stopwatch.setObjectName(u"btn_stop_stopwatch")
        self.btn_stop_stopwatch.setGeometry(QRect(170, 180, 131, 51))
        self.btn_stop_stopwatch.setFont(font4)
        self.btn_stop_stopwatch.setStyleSheet(u"background-color: rgb(85, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.btn_reset_stopwatch = QPushButton(self.tab_4)
        self.btn_reset_stopwatch.setObjectName(u"btn_reset_stopwatch")
        self.btn_reset_stopwatch.setGeometry(QRect(310, 180, 131, 51))
        self.btn_reset_stopwatch.setFont(font4)
        self.btn_reset_stopwatch.setStyleSheet(u"background-color: rgb(255, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Clock", None))
        self.menu_new.setText(QCoreApplication.translate("MainWindow", u"New...", None))
        self.menu_open.setText(QCoreApplication.translate("MainWindow", u"Open File", None))
        self.menu_about.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.menu_exit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.menu_solve.setText(QCoreApplication.translate("MainWindow", u"Solve sudoku", None))
        self.menu_help.setText(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menu_theme.setText(QCoreApplication.translate("MainWindow", u"Switch Theme", None))
        self.lbl_clock_iran.setText(QCoreApplication.translate("MainWindow", u"88:88:88", None))
        self.lbl_clock_germany.setText(QCoreApplication.translate("MainWindow", u"88:88:88", None))
        self.lbl_clock_usa.setText(QCoreApplication.translate("MainWindow", u"88:88:88", None))
        self.lbl_iran.setText(QCoreApplication.translate("MainWindow", u"Tehran:", None))
        self.lbl_germany.setText(QCoreApplication.translate("MainWindow", u"Berlin:", None))
        self.lbl_usa.setText(QCoreApplication.translate("MainWindow", u"NewYork:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"World Clock", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Alarm", None))
        self.btn_reset_timer.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.btn_start_timer.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.btn_stop_timer.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.tb_hour_timer.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.tb_minute_timer.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.tb_second_timer.setText(QCoreApplication.translate("MainWindow", u"30", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Timer", None))
        self.lbl_stopwatch.setText(QCoreApplication.translate("MainWindow", u"0:0:0", None))
        self.btn_start_stopwatch.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.btn_stop_stopwatch.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.btn_reset_stopwatch.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"StopWatch", None))
    # retranslateUi

